services:
  db:
    image: mysql:8.0
    container_name: poll_service_db
    environment:
      - MYSQL_DATABASE=poll_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d
      - poll_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  poll_db_data:

